bookers/config/routes.rb
Rails.application.routes.draw do
  get root to: 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = 'Book was successfully destroyed.'
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/views/books/edit.html.erb
<h1><strong>Editing Book</strong></h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
  <div class="field">
    <label>Titlel</label>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <label>Body</label>
    <%= f.text_area :body %>
  </div>
  <div class="button"><%= f.submit 'Update Book' %></div>
<% end %>

<span><%= link_to 'Show', book_path %> | <%= link_to 'Back', books_path %></span>

bookers/app/views/books/index.html.erb
<h1><strong>Books</strong></h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>
  <% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to 'Show', book_path(book.id) %></td>
    <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
    <td><%= link_to 'Destroy', book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
  </tr>
  <% end %>
</table>

<h2><strong>New book</strong></h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, method: :post do |f| %>
  <div class="field">
    <label>Titlel</label>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <label>Body</label>
    <%= f.text_area :body %>
  </div>
  <div class="button"><%= f.submit 'Create Book' %></div>
<% end %>

bookers/app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

bookers/app/views/books/show.html.erb
<p><strong>Title: </strong><%= @book.title %></p>

<p><strong>Body: </strong><%= @book.body %></p>

<span><%= link_to "Edit", edit_book_path %> | <%= link_to "Back", books_path %></span>

bookers/app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong> へ！</h1>

<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<p><%= link_to 'start', books_path %></p>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="text-success">
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </body>
</html>